baseURL = 'https://acfal2025.github.io/'
languageCode = 'en-us'
title = 'Bioinformatics Site'
theme = "ananke"

[params.math]
enable = true

[author]
name = "Anlin Feng"
bio = "I write about tech, life, and science."
avatar = "img/sunrise.jpeg"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 3

[params]
darkMode = true
